# Tensorflow2.0 小练习

In [13]:
import tensorflow as tf
import numpy as np

## 实现softmax函数

In [14]:
def softmax(x):
    ##########
    '''实现softmax函数，只要求对最后一维归一化，
    不允许用tf自带的softmax函数'''
    exp_x = tf.exp(x)
    # print("exp_x:", exp_x)
    sum_exp_x = tf.reduce_sum(exp_x, axis=-1, keepdims=True)
    # print("sum_exp_x:", sum_exp_x)
    prob_x = exp_x / sum_exp_x
    # print("prob_x:", prob_x)
    ##########
    return prob_x

test_data = np.random.normal(size=[10, 5])
(softmax(test_data).numpy() - tf.nn.softmax(test_data, axis=-1).numpy())**2 <0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现sigmoid函数

In [15]:
def sigmoid(x):
    ##########
    '''实现sigmoid函数， 不允许用tf自带的sigmoid函数'''
    # print("x:", x)
    prob_x = 1 / (1 + tf.exp(-x))
    # print("prob_x:", prob_x)    
    ##########
    return prob_x

test_data = np.random.normal(size=[10, 5])
(sigmoid(test_data).numpy() - tf.nn.sigmoid(test_data).numpy())**2 < 0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现 softmax 交叉熵loss函数

In [ ]:
def softmax_ce(x, label):
    ##########
    '''实现 softmax 交叉熵loss函数， 不允许用tf自带的softmax_cross_entropy函数'''
    log_prob_x = tf.math.log(x+10e-8)
    loss = - tf.reduce_sum(label * log_prob_x, axis=-1)
    loss = tf.reduce_mean(loss)
    ##########
    return loss

test_data = np.random.normal(size=[10, 5])
prob = tf.nn.softmax(test_data)
label = np.zeros_like(test_data)
label[np.arange(10), np.random.randint(0, 5, size=10)]=1.


((tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(label, test_data))
  - softmax_ce(prob, label))**2 < 0.0001).numpy()


loss: tf.Tensor(
[2.67358684 2.04877877 1.85048888 1.20806149 3.10078736 2.28866556
 2.07962474 1.61305097 2.43210499 1.87479337], shape=(10,), dtype=float64)
loss: tf.Tensor(2.116994296698033, shape=(), dtype=float64)


np.True_

## 实现 sigmoid 交叉熵loss函数

In [35]:
def sigmoid_ce(x, label):
    ##########
    '''实现 softmax 交叉熵loss函数， 不允许用tf自带的softmax_cross_entropy函数'''
    log_prob_x = tf.math.log(x+10e-8)
    loss = -(label * log_prob_x + (1-label) * tf.math.log(1-x+10e-8))
    loss = tf.reduce_mean(loss)
    ##########
    return loss

test_data = np.random.normal(size=[10])
prob = tf.nn.sigmoid(test_data)
label = np.random.randint(0, 2, 10).astype(test_data.dtype)
print (label)

((tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(label, test_data))- sigmoid_ce(prob, label))**2 < 0.0001).numpy()


[0. 1. 1. 1. 0. 0. 0. 0. 1. 1.]


np.True_